defaults:
  - /module@module: basic_module_config
  - /dataloader@test_dataloader: test_data_config
  - /trainer@trainer: trainer_config

seed: 42

hydra:
  run:
    dir: ./outputs/test

proj_dir: .
train_or_test: test

ckpt_path: ???
# ckpt_path: ${proj_dir}/outputs/train/tblog/lightning_logs/L0_lambda1.0_reg0.3151/checkpoints/last.ckpt

without_using_gate: false # Neither true or false will not effect the l0gate parameters anyway
# Won't affect the test results, just for parsing model
lambda_l0: 0.5
droprate_init: 0.5