defaults:
  - /module@module: basic_module_config
  - /dataloader@test_dataloader: test_data_config
  - /trainer@trainer: trainer_config

seed: 42

hydra:
  run:
    dir: ./outputs/test

proj_dir: .
train_or_test: test

ckpt_path: ???
# ckpt_path: ${proj_dir}/outputs/train/tblog/lightning_logs/train_from_scratch_with_l0/checkpoints/last.ckpt

without_using_gate: false # Neither true or false will not effect the l0gate parameters anyway