defaults:
  - /module@module: basic_module_config
  - /dataloader@train_dataloader: train_data_config
  - /dataloader@val_dataloader: val_data_config
  - /dataloader@test_dataloader: test_data_config
  - /trainer@trainer: trainer_config

seed: 42

hydra:
  run:
    dir: ./outputs/train

proj_dir: .
train_or_test: train

# ckpt_path: null
ckpt_path: ${proj_dir}/outputs/train/tblog/lightning_logs/version_0/checkpoints/last.ckpt
resume_training: false # will be ignored if ckpt_path is null

# Control using the L0-gate
# if false (i.e.set gate params become learable), then `resume_training` should be false, or will pop Error
without_using_gate: false