_target_: pytorch_lightning.Trainer
callbacks:
  # Save the best checkpoint based on the maximum val_acc recorded. Saves only weights and not optimizer
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    # save_weights_only: true # set true will loss the status buffer/parameters in optimizer/scheduler
    mode: max
    monitor: val_acc
    save_top_k: -1
    save_last: true
  # Log learning rate every epoch
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: epoch
logger:
  - _target_: pytorch_lightning.loggers.TensorBoardLogger
    save_dir: ./tblog
gpus: 1
max_epochs: 180
